TARGET = Cpp_HLTRGB_3_Overlay

OPENCV_INC_PATH = -I/usr/local/include/opencv4
OPENCV_LIB_PATH = -L/usr/local/lib
OPENCV_LIBS = -lopencv_core -lopencv_features2d -lopencv_imgproc -lopencv_calib3d -lopencv_videoio -lopencv_imgcodecs

include ../common.mk
